### PR TITLE
[Fix] Add missing max_token in request query

### LINKED ISSUE #31: [BUG] `max_tokens` seems to have no effeect on the output
running on latest main commit (local build)

setting `max_tokens` to something low like 20 will still output long text

```
name: openai
api_key: <redacted>
model: gpt-4-turbo-preview
max_tokens: 20
role: You are a developer
temperature: 1
top_p: 1
frequency_penalty: 0
presence_penalty: 0
thread: default
omit_history: false
url: https://api.openai.com
completions_path: /v1/chat/completions
models_path: /v1/models
auth_header: Authorization
auth_token_prefix: 'Bearer '
```

### PR DESCRIPTION
**Pull request by nopeless**
fixes #31

### CODE REVIEW

**Comment by kardolus** [comment]
@nopeless thank you so much for this! I will either merge this in and then fix the tests after or I will suggest a patch. I'm hoping to find some time today or tomorrow.

**Comment by nopeless** [comment]
whoops, forgot tests existed. I only tested manually

**Comment by nopeless** [comment]
@kardolus also if it helps with context, i find myself using the query mode for batch jobs. that is why i need the max token on the output

**Comment by kardolus** [comment]
@nopeless here's a patch that fixes the tests. Do you want to apply it? I can do it to after the merge, but it would be nice to keep the main branch green. 


[0001-fix-add-missing-max_token-in-request-query.patch](https://github.com/kardolus/chatgpt-cli/files/14675824/0001-fix-add-missing-max_token-in-request-query.patch)

**Comment by nopeless** [comment]
@kardolus i can apply that patch but i am also pretty sure that you can modify the pr itself

**Comment by nopeless** [comment]
allow edits by maintainers is checked

**Comment by kardolus** [comment]
@nopeless ah gotcha, either is fine by me. I just updated the patch btw :). Added the wrong file earlier.

**Comment by kardolus** [comment]
Thank you!

**Pull request merged**
