### PR TITLE
Add config for custom prompt

### PR DESCRIPTION
**Pull request by catskull**
Great project! Having fun with it.

This is my first time using Go but the docs and code are succinct enough I was able to manage without much hassle. Great job!

Ideally you would be able to use the timestamp and counter variables with some placeholders in the custom prompt string, but I couldn't figure that out and this fits my use case.

"prompt" has some conflated meaning in this context but I chose that since the code was already calling it that. :)

### CODE REVIEW

**Comment by kardolus** [comment]
@catskull this is great! I am glad you're having fun playing with the code base. 

I just cloned your repo to play around with it as well. I said it to "test" and it worked. Will think about variables. 

I was thinking, we may want to go with a different name (instead of `prompt`). In the future I want to support "prompts" (very overloaded i know) in the same style as in this great repo: https://github.com/danielmiessler/fabric

Can't think of a good name just yet. Any ideas?

**Comment by catskull** [comment]
Maybe `commandPrompt`?

https://en.wikipedia.org/wiki/Command-line_interface#Command_prompt

**Comment by kardolus** [comment]
@catskull That sounds great, we will have to snake it in the config file `command_prompt` just to be consistent. But that sounds good!

**Comment by kardolus** [comment]
@catskull PS I am also happy to merge this in and make the change myself. No pressure! :). I will check back  in tomorrow evening.

**Comment by catskull** [comment]
@kardolus PR updated! 🤓

**Pull request merged**
