### PR TITLE
docs: windows build script

### PR DESCRIPTION
**Pull request by nopeless**
I like to build my things

### CODE REVIEW

**Comment by kardolus** [comment]
I haven't used windows since XP so I may ask dumb questions :)

My question is, what's the output of the `./scripts/install.sh` or the `reinstall.sh` script in `powershell`?

I created the `binaries.sh` script to create releases for all environments. Just for my own box I use `install` and `reinstall`

**Comment by kardolus** [comment]
PS thanks! This is great. Having something for powershell folks is great!

**Comment by kardolus** [comment]
I'm also curious what `make install` or `make reinstall` outputs are in powershell. Can you execute Makefiles in windows? Sorry for my ignorance.

**Comment by nopeless** [comment]
> I'm also curious what `make install` or `make reinstall` outputs are in powershell. Can you execute Makefiles in windows? Sorry for my ignorance.

Its do-able as far as I know (I guess with combination of gnuwin32's make and git's bash would work?) but I would rather just use wsl if I need to use makefiles.

output
```text
 .\scripts\binaries.ps1
Building chatgpt for windows/amd64...done
```

**Comment by nopeless** [comment]
I only made the binaries.sh for powershell because the other script files I couldn't get gexec to work properly and I don't have enough time to debug it right now. Being able to build locally was still a feat in my head so I made the pr

**Comment by kardolus** [comment]
Gotcha. I guess this is a good start and we can iterate from here. Thank you!

**Comment by kardolus** [comment]
@nopeless I renamed it to `install.ps1` just to be consistent. Let me know if that broke something.

**Pull request merged**
