### PR TITLE
Add o1 compatibility

### PR DESCRIPTION
**Pull request by bezmi**
commit `1a59226`: add a `no_system` user config option, which sets Config.NoSystem. If true, then the system role message is not appended to the history in the `initHistory` function.

commit `648c6e2`: rename `max_tokens` to `max_completion_tokens` in `api/completions.go`, since `max_tokens` is deprecated and doesn't work with the new (o1) models. I have no idea if this breaks non OpenAI APIs.

Happy push some documentation before merge, after sorting out any comments/changes by the maintainers.

note: setting `no_system` in `config.yaml` disables the `role` option, but there is no warning that it is being ignored (if the user has set both).

Tested with the OpenAI models (mostly `o1-preview` and `gpt-4o`) and it works just fine.

### CODE REVIEW

**Comment by kardolus** [comment]
Thanks! I will look into this over the weekend (it's a holiday week and I'm traveling). 

I have been using `4o` for a while and have not looked into `o1`. We will have to make sure we are backwards compatible. Let me read up on the API configuration before merging this in :). 

Looks promising though!

**Comment by bezmi** [comment]
Thanks for the quick response.

With the `max_completion_tokens` change, the OpenAI models are operating the same as before. [The chat completion API reference](https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens)  implies that they represent the same thing, except that the newer one includes reasoning tokens as well. I'm 99% sure this breaks the other (perplexity) APIs. Might not be the end of the world as your final comment in #56 implies you're working on proper compatibility in a separate code.

Setting 'no_system` to `true` in the user configuration with `gpt-4o` also works as expected. The message is sent with the user prompt only, and the model returns a response.

**Comment by kardolus** [comment]
I see I see. Thanks for explaining! 

We may want to use the `omitempty` annotation and have both fields available. In this way you can use both old and new APIs. Let me see how old GPT models work with the new param though. If it's backwards compatible already it would save us some time. 

We can also look into using a migration script to migrate folks their current config into a new configuration. I have done so before so we can just add to the existing logic.

**Comment by bezmi** [comment]
> We may want to use the omitempty annotation
You would still need logic to determine when to send `max_tokens` vs `max_completion_tokens` right?

**Comment by kardolus** [comment]
> > We may want to use the omitempty annotation
> 
> You would still need logic to determine when to send `max_tokens` vs `max_completion_tokens` right?

Yeah, or we can make both configurable. That would be odd though.

**Comment by kardolus** [comment]
@bezmi quick question, where is `no_system` documented? I just went over the documentation but cannot find it. I just realized I have to update `--list-models` as well

**Comment by kardolus** [comment]
I updated `--list-models`. Just need to make sure we need `no_system`. Will also test with perplexity and llama.

**Comment by kardolus** [comment]
@bezmi I updated the `no_system` part in order to make the history portable across models and llms. Will merge this in later today. Just want to test against perplexity and llama.

**Comment by kardolus** [comment]
Well, llama and perplexity don't throw errors. Not sure if they still work the same though! :). I feel ok merging this in. 

Thanks for helping out!!

**Pull request merged**
